### ISSUE TITLE
Would be possible to enable Wake on LAN and Restore Last Power State?

### ISSUE THREAD

**Issue by jairov4** [BIOS-iEngineer/Jingsha-X99-Dual#1]
Those features are not available in stock bios, and I feel thats the cherry 🍒  missing in the cake.
Do you see that possible? Or maybe you can point some documentation to start hacking the bios building for this kind of mobo so maybe some of us can help on this?

**Comment by BIOS-iEngineer** [comment]
This BIOS is not related to any BIOS from China. If you need extra functionality, you can try adding it yourself. The source code for the BIOS modules will never be published or shared with anyone.
