### ISSUE TITLE
System boots not from the first time

### ISSUE THREAD

**Issue by idev1669** [BIOS-iEngineer/Jingsha-X99-Dual#3]
System boots not from the first time crashes on ACPI Tables, started with installing pic wifi-bluetooth combo module. issue is 100% in bios because I swapped module and gpu and power supply problem is still on. With modified bioses from net users problem is not going away or just changing to another(Acpi tables pass and it breaks on working with pci devices again).
As I understood it happened because above 4g function is not working correctly.

**Comment by BIOS-iEngineer** [comment]
You can enable this feature using the AMIBCP utility.
Or use BIOS for SZMZ X99 Dual Z8 then the built-in VGA adapter will not work.

**Comment by idev1669** [comment]
> You can enable this feature using the AMIBCP utility.
> Or use BIOS for SZMZ X99 Dual Z8 then the built-in VGA adapter will not work.

I've enabled this feature in bios it just doesn't work(I get black screen) helps only bios reset with battery

**Comment by BIOS-iEngineer** [comment]
Perhaps the board needs some work. I do not have this board, this bios was made remotely, the ordering party had no problems with this bios and they had about 50 of these boards.

**Comment by idev1669** [comment]
> Perhaps the board needs some work. I do not have this board, this bios was made remotely, the ordering party had no problems with this bios and they had about 50 of these boards.

probably they don't use more than one pci port, cause I found that this problem exists only when I inserted BCM94360CD wifi+bluetoth combo module.
ps. I tried another pci module that was working in another pc, problem didn't go away.
anyway thanks for trying to help

**Comment by BIOS-iEngineer** [comment]
Module BCM943224PCIEBT2 worked with a similar SZMZ board, without compatibility problems.

**Comment by ForeverAlone2009** [comment]
> Module BCM943224PCIEBT2 worked with a similar SZMZ board, without compatibility problems.

Does your bios have all the fixes made by this guy?
https://vk.com/@2485616-2x-lga2011-3-jingsha-bq36-v11

I cannot enable turbo boost unlock in any bios of this motherboard.

**Comment by BIOS-iEngineer** [comment]
ForeverAlone2009, I have no idea what this guy is doing.
You probably went to the wrong place, I don't provide any advice turbo boost unlock.
